default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV["DB_PASSWORD"] %>
  database: <%= ENV.fetch("DB_DATABASE", "furima_46817_development") %>
<% if ENV["DB_SOCKET"].present? %>
  socket: <%= ENV["DB_SOCKET"] %>
<% else %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
<% end %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_DATABASE", "furima_46817_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_DATABASE", "furima_46817_test") %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>
